"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Users, TrendingUp, DollarSign, ShoppingBag, Zap, AlertCircle, Sparkles, Calendar, ChevronLeft, ChevronRight, Target, Crown, UserMinus, Clock, Filter, Search, History, ArrowUpRight } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { useState, useEffect } from "react"
import { Skeleton } from "@/components/ui/skeleton"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip"

export default function CustomersPage() {
    const [stats, setStats] = useState<any>(null)
    const [customers, setCustomers] = useState<any[]>([])
    const [isLoading, setIsLoading] = useState(true)
    const [isListLoading, setIsListLoading] = useState(true)
    const [isGenerating, setIsGenerating] = useState(false)
    const [hasAutoGenerated, setHasAutoGenerated] = useState(false) // NEW: Prevent duplicate auto-generation
    const [page, setPage] = useState(1)
    const [total, setTotal] = useState(0)
    const limit = 10

    useEffect(() => {
        async function fetchStats() {
            try {
                const res = await fetch("/api/dashboard/stats")
                if (res.ok) {
                    const data = await res.json()
                    setStats(data)
                }
            } catch (error) {
                console.error("Failed to fetch stats", error)
            } finally {
                setIsLoading(false)
            }
        }
        fetchStats()
    }, [])

    useEffect(() => {
        async function fetchCustomers() {
            setIsListLoading(true)
            try {
                // Fetch AI-enriched profiles
                const res = await fetch(`/api/customers/profiles`)
                if (res.ok) {
                    const data = await res.json()
                    const profiles = data.profiles || []
                    setCustomers(profiles)
                    setTotal(profiles.length)
                    
                    // Auto-generate profiles if none exist (only once)
                    if (profiles.length === 0 && !hasAutoGenerated) {
                        console.log("[Customers] No profiles found, auto-generating...")
                        setHasAutoGenerated(true) // Prevent duplicate calls
                        setIsGenerating(true)
                        try {
                            const generateRes = await fetch("/api/customers/generate-profiles", { method: "POST" })
                            const generateData = await generateRes.json()
                            
                            if (generateRes.ok && generateData.success) {
                                // Refresh the customer list after generation
                                const refreshRes = await fetch(`/api/customers/profiles`)
                                if (refreshRes.ok) {
                                    const refreshData = await refreshRes.json()
                                    setCustomers(refreshData.profiles || [])
                                    setTotal(refreshData.profiles?.length || 0)
                                }
                            }
                        } catch (error) {
                            console.error("Auto-generate profiles failed:", error)
                            setHasAutoGenerated(false) // Reset on error to allow retry
                        } finally {
                            setIsGenerating(false)
                        }
                    }
                }
            } catch (error) {
                console.error("Failed to fetch customers", error)
            } finally {
                setIsListLoading(false)
            }
        }

        fetchCustomers()
    }, [hasAutoGenerated])

    const handleGenerateProfiles = async () => {
        setIsGenerating(true)
        try {
            const res = await fetch("/api/customers/generate-profiles", { method: "POST" })
            const data = await res.json()
            
            if (res.ok && data.success) {
                const profileCount = data.stats?.profiles_generated || data.profiles_generated || 0
                alert(`✅ Success! Generated ${profileCount} customer profiles`)
                // Refresh the customer list
                const refreshRes = await fetch(`/api/customers/profiles`)
                if (refreshRes.ok) {
                    const refreshData = await refreshRes.json()
                    setCustomers(refreshData.profiles || [])
                    setTotal(refreshData.profiles?.length || 0)
                }
            } else {
                // Handle both error responses and success=false cases
                const errorMsg = data.message || data.error || 'Failed to generate profiles'
                alert(`⚠️ ${errorMsg}`)
            }
        } catch (error) {
            console.error("Failed to generate profiles", error)
            alert("❌ Failed to generate customer profiles")
        } finally {
            setIsGenerating(false)
        }
    }

    // Calculate segments for the matrix from the fetched profiles
    const matrixSegments = [
        { name: "Champions", count: customers.filter(c => c.segment === 'Champions').length, icon: <Crown className="h-4 w-4 text-yellow-500" />, color: "text-yellow-500", bg: "bg-yellow-500/5" },
        { name: "Loyalists", count: customers.filter(c => c.segment === 'Loyalists').length, icon: <Target className="h-4 w-4 text-blue-500" />, color: "text-blue-500", bg: "bg-blue-500/5" },
        { name: "At-Risk", count: customers.filter(c => c.segment === 'At-Risk').length, icon: <Clock className="h-4 w-4 text-orange-500" />, color: "text-orange-500", bg: "bg-orange-500/5" },
        { name: "Lost", count: customers.filter(c => c.segment === 'Lost').length, icon: <UserMinus className="h-4 w-4 text-red-500" />, color: "text-red-500", bg: "bg-red-500/5" }
    ]

    // Calculate real retention forecast metrics from customer data
    const avgLTV = customers.length > 0 ? customers.reduce((sum, c) => sum + (c.ltv || 0), 0) / customers.length : 0;
    const avgChurnRisk = customers.length > 0 ? customers.reduce((sum, c) => sum + (c.churnRisk || 0), 0) / customers.length : 0;
    const highValueCustomers = customers.filter(c => c.segment === 'Champions' || c.segment === 'Loyalists').length;
    const ltvGrowthPct = highValueCustomers > 0 ? ((highValueCustomers / customers.length) * 100).toFixed(1) : "0";
    const churnRiskLevel = avgChurnRisk > 0.7 ? "HIGH" : avgChurnRisk > 0.4 ? "MEDIUM" : "LOW";
    const churnRiskColor = avgChurnRisk > 0.7 ? "text-red-500" : avgChurnRisk > 0.4 ? "text-orange-500" : "text-green-500";

    return (
        <div className="p-6 space-y-6 max-w-[1600px] mx-auto">
            {/* Header Section */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h1 className="text-2xl font-bold tracking-tight">Customers</h1>
                    <p className="text-sm text-muted-foreground">Manage relationships and track customer intelligence.</p>
                </div>
                <div className="flex items-center gap-2">
                    <Button variant="outline" size="sm" className="rounded-xl h-9">Export CSV</Button>
                    <Button 
                        size="sm" 
                        className="rounded-xl h-9 gap-2 shadow-lg shadow-primary/20"
                        onClick={handleGenerateProfiles}
                        disabled={isGenerating}
                    >
                        <Zap className="h-3.5 w-3.5" />
                        {isGenerating ? "Generating..." : "Generate Profiles"}
                    </Button>
                </div>
            </div>

            {/* No Data Alert */}
            {!isListLoading && customers.length === 0 && (
                <Card className="border-2 border-dashed border-muted-foreground/20 bg-muted/30">
                    <CardContent className="flex flex-col items-center justify-center py-12 text-center space-y-4">
                        <div className="p-4 rounded-full bg-primary/10">
                            <Users className="h-8 w-8 text-primary" />
                        </div>
                        <div className="space-y-2">
                            <h3 className="text-lg font-semibold">No Customer Profiles Yet</h3>
                            <p className="text-sm text-muted-foreground max-w-md">
                                Connect your store and sync data to start generating AI-powered customer insights.
                            </p>
                        </div>
                        <div className="flex items-center gap-3">
                            <Button 
                                variant="outline" 
                                size="sm"
                                onClick={() => window.location.href = '/dashboard'}
                                className="rounded-xl"
                            >
                                Go to Dashboard
                            </Button>
                            <Button 
                                size="sm" 
                                onClick={handleGenerateProfiles}
                                disabled={isGenerating}
                                className="rounded-xl gap-2"
                            >
                                <Zap className="h-3.5 w-3.5" />
                                {isGenerating ? "Generating..." : "Try Generate"}
                            </Button>
                        </div>
                    </CardContent>
                </Card>
            )}

            {/* Main Layout Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">

                {/* Left Column: Core Stats & Table */}
                <div className="lg:col-span-9 space-y-6">

                    {/* Compact Core Stats */}
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                        {[
                            { label: "Total Base", value: stats?.totalCustomers || 0, icon: <Users className="h-4 w-4" />, sub: "Unique users" },
                            { label: "Revenue", value: `$${(stats?.totalSales || 0).toLocaleString()}`, icon: <DollarSign className="h-4 w-4" />, sub: "Lifetime value" },
                            { label: "Orders", value: stats?.totalOrders || 0, icon: <ShoppingBag className="h-4 w-4" />, sub: "Transactions" },
                            { label: "Avg. LTV", value: `$${stats?.totalCustomers ? Math.round(stats.totalSales / stats.totalCustomers) : 0}`, icon: <TrendingUp className="h-4 w-4" />, sub: "Per customer" }
                        ].map((s, i) => (
                            <Card key={i} className="rounded-2xl border-border shadow-sm overflow-hidden">
                                <CardContent className="p-4 flex items-center gap-4">
                                    <div className="h-10 w-10 rounded-xl bg-muted/50 flex items-center justify-center text-muted-foreground">
                                        {s.icon}
                                    </div>
                                    <div>
                                        <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{s.label}</p>
                                        <div className="text-lg font-bold">{isLoading ? <Skeleton className="h-6 w-16" /> : s.value}</div>
                                    </div>
                                </CardContent>
                            </Card>
                        ))}
                    </div>

                    {/* Customer Table Card */}
                    <Card className="rounded-2xl border-border shadow-sm overflow-hidden">
                        <CardHeader className="p-5 border-b bg-muted/5 flex flex-row items-center justify-between space-y-0">
                            <div className="flex items-center gap-4">
                                <CardTitle className="text-sm font-bold">Directory</CardTitle>
                                <div className="relative w-64 hidden md:block">
                                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
                                    <Input placeholder="Search customers..." className="pl-9 h-8 rounded-lg text-xs bg-background border-border" />
                                </div>
                            </div>
                            <div className="flex items-center gap-2">
                                <Button variant="outline" size="sm" className="h-8 rounded-lg text-xs gap-2">
                                    <Filter className="h-3 w-3" />
                                    Filter
                                </Button>
                                <Badge variant="secondary" className="rounded-lg text-[10px] font-bold px-2 py-0.5">
                                    {total} Top Profiles
                                </Badge>
                            </div>
                        </CardHeader>
                        <CardContent className="p-0">
                            <Table>
                                <TableHeader className="bg-muted/20">
                                    <TableRow className="hover:bg-transparent border-border">
                                        <TableHead className="font-bold text-[10px] uppercase tracking-wider p-4">Customer</TableHead>
                                        <TableHead className="font-bold text-[10px] uppercase tracking-wider p-4">AI Segment</TableHead>
                                        <TableHead className="font-bold text-[10px] uppercase tracking-wider p-4">Churn Risk</TableHead>
                                        <TableHead className="text-right font-bold text-[10px] uppercase tracking-wider p-4">LTV Score</TableHead>
                                    </TableRow>
                                </TableHeader>
                                <TableBody>
                                    {isListLoading ? (
                                        Array(limit).fill(0).map((_, i) => (
                                            <TableRow key={i}>
                                                <TableCell className="p-4"><Skeleton className="h-10 w-full rounded-lg" /></TableCell>
                                                <TableCell className="p-4"><Skeleton className="h-10 w-full rounded-lg" /></TableCell>
                                                <TableCell className="p-4"><Skeleton className="h-10 w-full rounded-lg" /></TableCell>
                                                <TableCell className="p-4"><Skeleton className="h-10 w-full rounded-lg" /></TableCell>
                                            </TableRow>
                                        ))
                                    ) : customers.length > 0 ? (
                                        customers.map((customer, i) => {
                                            const isChampion = customer.segment === 'Champions';
                                            const isAtRisk = customer.segment === 'At-Risk' || customer.churnRisk > 0.7;
                                            const isLoyalist = customer.segment === 'Loyalists';

                                            return (
                                                <TableRow key={i} className="hover:bg-muted/10 border-border transition-colors group">
                                                    <TableCell className="p-4">
                                                        <div className="flex items-center gap-3">
                                                            <Avatar className="h-8 w-8 rounded-lg border border-border shadow-sm">
                                                                <AvatarFallback className="bg-primary/5 text-primary font-bold text-[10px]">
                                                                    {customer.customerName?.split(' ').map((n: any) => n[0]).join('') || 'C'}
                                                                </AvatarFallback>
                                                            </Avatar>
                                                            <div className="flex flex-col">
                                                                <span className="font-bold text-xs">{customer.customerName}</span>
                                                                <span className="text-[9px] text-muted-foreground">ID: {customer.customerId}</span>
                                                            </div>
                                                        </div>
                                                    </TableCell>
                                                    <TableCell className="p-4">
                                                        <div className="flex flex-wrap gap-1.5">
                                                            {isChampion ? (
                                                                <Badge className="bg-yellow-500/10 text-yellow-600 border-none rounded-md text-[9px] font-bold px-1.5 py-0.5 flex items-center gap-1">
                                                                    <Crown className="h-2.5 w-2.5" /> CHAMPION
                                                                </Badge>
                                                            ) : isAtRisk ? (
                                                                <Badge className="bg-red-500/10 text-red-600 border-none rounded-md text-[9px] font-bold px-1.5 py-0.5 flex items-center gap-1">
                                                                    <AlertCircle className="h-2.5 w-2.5" /> AT-RISK
                                                                </Badge>
                                                            ) : isLoyalist ? (
                                                                <Badge variant="outline" className="rounded-md text-[9px] font-bold px-1.5 py-0.5 border-border flex items-center gap-1">
                                                                    <Target className="h-2.5 w-2.5" /> LOYALIST
                                                                </Badge>
                                                            ) : (
                                                                <Badge variant="secondary" className="rounded-md text-[9px] font-bold px-1.5 py-0.5">
                                                                    {customer.segment || 'Unknown'}
                                                                </Badge>
                                                            )}
                                                        </div>
                                                    </TableCell>
                                                    <TableCell className="p-4">
                                                        <div className="flex items-center gap-2">
                                                            <div className="h-1.5 w-16 bg-muted rounded-full overflow-hidden">
                                                                <div
                                                                    className={`h-full rounded-full ${customer.churnRisk > 0.7 ? 'bg-red-500' :
                                                                            customer.churnRisk > 0.4 ? 'bg-orange-500' : 'bg-green-500'
                                                                        }`}
                                                                    style={{ width: `${customer.churnRisk * 100}%` }}
                                                                />
                                                            </div>
                                                            <span className={`text-[10px] font-bold ${customer.churnRisk > 0.7 ? 'text-red-500' : 'text-muted-foreground'
                                                                }`}>
                                                                {Math.round(customer.churnRisk * 100)}%
                                                            </span>
                                                        </div>
                                                    </TableCell>
                                                    <TableCell className="p-4 text-right">
                                                        <div className="flex flex-col items-end gap-0.5">
                                                            <span className="font-bold text-xs">{customer.rfmScore?.total || 0} pts</span>
                                                            <span className="text-[9px] text-muted-foreground font-medium">
                                                                LTV: ${Math.round(customer.ltv || 0).toLocaleString()}
                                                            </span>
                                                        </div>
                                                    </TableCell>
                                                </TableRow>
                                            );
                                        })
                                    ) : (
                                        <TableRow>
                                            <TableCell colSpan={4} className="p-10 text-center">
                                                <div className="flex flex-col items-center gap-3">
                                                    <Sparkles className="h-10 w-10 text-muted-foreground/30" />
                                                    <div>
                                                        <p className="text-sm font-semibold text-foreground mb-1">No customer profiles yet</p>
                                                        <p className="text-xs text-muted-foreground mb-3">
                                                            Click "Generate Profiles" above to run AI analysis on your customer data
                                                        </p>
                                                    </div>
                                                    <Button 
                                                        size="sm" 
                                                        className="rounded-xl gap-2"
                                                        onClick={handleGenerateProfiles}
                                                        disabled={isGenerating}
                                                    >
                                                        <Zap className="h-3.5 w-3.5" />
                                                        {isGenerating ? "Generating..." : "Generate Profiles Now"}
                                                    </Button>
                                                </div>
                                            </TableCell>
                                        </TableRow>
                                    )}
                                </TableBody>
                            </Table>
                        </CardContent>
                    </Card>
                </div>

                {/* Right Column: Intelligence Matrix (SaaS Style) */}
                <div className="lg:col-span-3 space-y-6">
                    <Card className="rounded-2xl border-border shadow-sm overflow-hidden">
                        <CardHeader className="p-5 border-b bg-muted/5">
                            <div className="flex items-center gap-2">
                                <Sparkles className="h-4 w-4 text-primary" />
                                <CardTitle className="text-sm font-bold uppercase tracking-wider">Intelligence Matrix</CardTitle>
                            </div>
                        </CardHeader>
                        <CardContent className="p-0 divide-y divide-border">
                            {matrixSegments.map((segment, idx) => (
                                <div key={idx} className="p-4 hover:bg-muted/30 transition-colors cursor-pointer group">
                                    <div className="flex items-center justify-between mb-1">
                                        <div className="flex items-center gap-2">
                                            <div className={`p-1.5 rounded-lg ${segment.bg}`}>
                                                {segment.icon}
                                            </div>
                                            <span className="text-xs font-bold">{segment.name}</span>
                                        </div>
                                        <span className="text-[10px] font-bold text-muted-foreground">{segment.count}</span>
                                    </div>
                                    <div className="flex items-center justify-between mt-2">
                                        <div className="h-1.5 flex-1 bg-muted rounded-full overflow-hidden mr-3">
                                            <div
                                                className={`h-full ${segment.color.replace('text', 'bg')} opacity-60`}
                                                style={{ width: `${(segment.count / (total || 100)) * 100}%` }}
                                            />
                                        </div>
                                        <span className="text-[9px] font-bold text-muted-foreground">{Math.round((segment.count / (total || 100)) * 100)}%</span>
                                    </div>
                                </div>
                            ))}
                        </CardContent>
                        <div className="p-4 bg-primary/5 border-t border-border">
                            <div className="flex items-start gap-2">
                                <Zap className="h-3 w-3 text-primary mt-0.5" />
                                <p className="text-[10px] text-muted-foreground leading-relaxed">
                                    AI segments are updated in real-time based on purchase frequency.
                                </p>
                            </div>
                        </div>
                    </Card>

                    {/* Retention Forecast Card */}
                    <Card className="rounded-2xl border-border shadow-sm bg-gradient-to-br from-primary/5 to-transparent">
                        <CardHeader className="p-5 pb-2">
                            <CardTitle className="text-xs font-bold uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                                <Calendar className="h-3.5 w-3.5" />
                                Retention Forecast
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="p-5 pt-0 space-y-4">
                            <div className="space-y-2">
                                <div className="flex justify-between text-[10px] font-bold">
                                    <span className="text-muted-foreground">HIGH-VALUE RATIO</span>
                                    <span className="text-green-500">{ltvGrowthPct}%</span>
                                </div>
                                <div className="h-1.5 w-full bg-muted rounded-full overflow-hidden">
                                    <div className="h-full bg-green-500 rounded-full" style={{ width: `${ltvGrowthPct}%` }} />
                                </div>
                            </div>
                            <div className="space-y-2">
                                <div className="flex justify-between text-[10px] font-bold">
                                    <span className="text-muted-foreground">AVG CHURN RISK</span>
                                    <span className={churnRiskColor}>{churnRiskLevel}</span>
                                </div>
                                <div className="h-1.5 w-full bg-muted rounded-full overflow-hidden">
                                    <div 
                                        className={`h-full rounded-full ${avgChurnRisk > 0.7 ? 'bg-red-500' : avgChurnRisk > 0.4 ? 'bg-orange-500' : 'bg-green-500'}`}
                                        style={{ width: `${Math.round(avgChurnRisk * 100)}%` }} 
                                    />
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>

            </div>
        </div>
    )
}
