"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Package, AlertCircle, TrendingUp, Sparkles, ShoppingCart, Brain, Zap, ArrowRight, BarChart3, ChevronLeft, ChevronRight, Search, Filter, Clock, Box, ArrowUpRight, DollarSign } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { useState, useEffect } from "react"
import { Skeleton } from "@/components/ui/skeleton"
import { Progress } from "@/components/ui/progress"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Input } from "@/components/ui/input"
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip"

export default function InventoryPage() {
    const [stats, setStats] = useState<any>(null)
    const [products, setProducts] = useState<any[]>([])
    const [isLoading, setIsLoading] = useState(true)
    const [isListLoading, setIsListLoading] = useState(true)
    const [isGenerating, setIsGenerating] = useState(false)
    const [hasAutoGenerated, setHasAutoGenerated] = useState(false)
    const [page, setPage] = useState(1)
    const [total, setTotal] = useState(0)
    const limit = 10

    useEffect(() => {
        async function fetchStats() {
            try {
                const res = await fetch("/api/dashboard/stats")
                if (res.ok) {
                    const data = await res.json()
                    setStats(data)
                }
            } catch (error) {
                console.error("Failed to fetch stats", error)
            } finally {
                setIsLoading(false)
            }
        }
        fetchStats()
    }, [])

    useEffect(() => {
        async function fetchProducts() {
            setIsListLoading(true)
            try {
                // Fetch AI inventory insights
                const res = await fetch(`/api/inventory/insights`)
                if (res.ok) {
                    const data = await res.json()
                    const insights = data.insights || []
                    setProducts(insights)
                    setTotal(insights.length)
                    
                    // Auto-generate insights if none exist (only once)
                    if (insights.length === 0 && !hasAutoGenerated && !isGenerating) {
                        console.log("[Inventory] No insights found, auto-generating...")
                        setHasAutoGenerated(true)
                        setIsGenerating(true)
                        try {
                            const generateRes = await fetch("/api/inventory/generate", { method: "POST" })
                            const generateData = await generateRes.json()
                            
                            if (generateRes.ok && generateData.success) {
                                // Refresh insights after generation
                                const refreshRes = await fetch(`/api/inventory/insights`)
                                if (refreshRes.ok) {
                                    const refreshData = await refreshRes.json()
                                    setProducts(refreshData.insights || [])
                                    setTotal(refreshData.insights?.length || 0)
                                }
                            } else if (generateRes.status === 429) {
                                // Another request is in progress, wait and retry
                                console.log("[Inventory] Generation in progress, waiting...");
                                await new Promise(resolve => setTimeout(resolve, 2000));
                                // Refresh to get results when ready
                                const refreshRes = await fetch(`/api/inventory/insights`)
                                if (refreshRes.ok) {
                                    const refreshData = await refreshRes.json()
                                    setProducts(refreshData.insights || [])
                                    setTotal(refreshData.insights?.length || 0)
                                }
                            }
                        } catch (error) {
                            console.error("Auto-generate inventory failed:", error)
                            setHasAutoGenerated(false)
                        } finally {
                            setIsGenerating(false)
                        }
                    }
                }
            } catch (error) {
                console.error("Failed to fetch inventory", error)
            } finally {
                setIsListLoading(false)
            }
        }

        fetchProducts()
    }, [hasAutoGenerated])

    // Calculate segments based on AI risk levels
    const matrixSegments = [
        { name: "Critical", count: products.filter(p => p.riskLevel === 'CRITICAL').length, icon: <AlertCircle className="h-4 w-4 text-red-500" />, color: "text-red-500", bg: "bg-red-500/5" },
        { name: "High Risk", count: products.filter(p => p.riskLevel === 'HIGH').length, icon: <TrendingUp className="h-4 w-4 text-orange-500" />, color: "text-orange-500", bg: "bg-orange-500/5" },
        { name: "Medium Risk", count: products.filter(p => p.riskLevel === 'MEDIUM').length, icon: <Box className="h-4 w-4 text-yellow-500" />, color: "text-yellow-500", bg: "bg-yellow-500/5" },
        { name: "Low Risk", count: products.filter(p => p.riskLevel === 'LOW').length, icon: <DollarSign className="h-4 w-4 text-green-500" />, color: "text-green-500", bg: "bg-green-500/5" }
    ]

    // Calculate real stock health metrics from product data
    const totalProducts = products.length || 1; // Avoid division by zero
    const productsInStock = products.filter(p => (p.currentStock || 0) > 0).length;
    const availabilityPct = Math.round((productsInStock / totalProducts) * 100);
    
    const criticalCount = products.filter(p => p.riskLevel === 'CRITICAL').length;
    const wasteRiskPct = Math.round((criticalCount / totalProducts) * 100);
    const wasteRiskLevel = wasteRiskPct > 20 ? "HIGH" : wasteRiskPct > 10 ? "MEDIUM" : "LOW";
    const wasteRiskColor = wasteRiskPct > 20 ? "text-red-500" : wasteRiskPct > 10 ? "text-orange-500" : "text-green-500";
    
    // Calculate turnover estimate (simplified: orders / products)
    const turnoverRate = stats?.totalOrders && stats?.totalProducts 
        ? (stats.totalOrders / stats.totalProducts).toFixed(1) 
        : "0.0";

    return (
        <div className="p-6 space-y-6 max-w-[1600px] mx-auto">
            {/* Header Section */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h1 className="text-2xl font-bold tracking-tight">Inventory</h1>
                    <p className="text-sm text-muted-foreground">Autonomous stock management and demand forecasting.</p>
                </div>
                <div className="flex items-center gap-2">
                    <Button variant="outline" size="sm" className="rounded-xl h-9">Export CSV</Button>
                    <Button 
                        size="sm" 
                        className="rounded-xl h-9 gap-2 bg-orange-500 hover:bg-orange-600 shadow-lg shadow-orange-500/20"
                        onClick={async () => {
                            if (isGenerating) return; // Prevent double-click
                            setIsGenerating(true);
                            try {
                                const res = await fetch("/api/inventory/generate", { method: "POST" });
                                const data = await res.json();
                                if (res.ok && data.success) {
                                    const refreshRes = await fetch(`/api/inventory/insights`);
                                    if (refreshRes.ok) {
                                        const refreshData = await refreshRes.json();
                                        setProducts(refreshData.insights || []);
                                        setTotal(refreshData.insights?.length || 0);
                                    }
                                } else if (res.status === 429) {
                                    console.log("[Inventory] Generation already in progress");
                                    // Don't show error, just wait for current generation to finish
                                }
                            } catch (error) {
                                console.error("Optimize stock failed:", error);
                            } finally {
                                setIsGenerating(false);
                            }
                        }}
                        disabled={isGenerating}
                    >
                        <Zap className="h-3.5 w-3.5" />
                        {isGenerating ? "Optimizing..." : "Optimize Stock"}
                    </Button>
                </div>
            </div>

            {/* Main Layout Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">

                {/* Left Column: Core Stats & Table */}
                <div className="lg:col-span-9 space-y-6">

                    {/* Compact Core Stats */}
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                        {[
                            { label: "Total SKUs", value: stats?.totalProducts || 0, icon: <Package className="h-4 w-4" />, sub: "Active products" },
                            { label: "Stock Value", value: `$${((stats?.totalSales || 0) * 0.4).toLocaleString()}`, icon: <DollarSign className="h-4 w-4" />, sub: "Inventory worth" },
                            { label: "Critical Items", value: products.filter(p => p.riskLevel === 'CRITICAL').length, icon: <AlertCircle className="h-4 w-4" />, sub: "Needs attention" },
                            { label: "Turnover", value: `${turnoverRate}x`, icon: <TrendingUp className="h-4 w-4" />, sub: "Annual rate" }
                        ].map((s, i) => (
                            <Card key={i} className="rounded-2xl border-border shadow-sm overflow-hidden">
                                <CardContent className="p-4 flex items-center gap-4">
                                    <div className="h-10 w-10 rounded-xl bg-muted/50 flex items-center justify-center text-muted-foreground">
                                        {s.icon}
                                    </div>
                                    <div>
                                        <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{s.label}</p>
                                        <div className="text-lg font-bold">{isLoading ? <Skeleton className="h-6 w-16" /> : s.value}</div>
                                    </div>
                                </CardContent>
                            </Card>
                        ))}
                    </div>

                    {/* Inventory Table Card */}
                    <Card className="rounded-2xl border-border shadow-sm overflow-hidden">
                        <CardHeader className="p-5 border-b bg-muted/5 flex flex-row items-center justify-between space-y-0">
                            <div className="flex items-center gap-4">
                                <CardTitle className="text-sm font-bold">Stock Directory</CardTitle>
                                <div className="relative w-64 hidden md:block">
                                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
                                    <Input placeholder="Search products..." className="pl-9 h-8 rounded-lg text-xs bg-background border-border" />
                                </div>
                            </div>
                            <div className="flex items-center gap-2">
                                <Button variant="outline" size="sm" className="h-8 rounded-lg text-xs gap-2">
                                    <Filter className="h-3 w-3" />
                                    Filter
                                </Button>
                                <Badge variant="secondary" className="rounded-lg text-[10px] font-bold px-2 py-0.5">
                                    {total} Risky Items
                                </Badge>
                            </div>
                        </CardHeader>
                        <CardContent className="p-0">
                            <Table>
                                <TableHeader className="bg-muted/20">
                                    <TableRow className="hover:bg-transparent border-border">
                                        <TableHead className="font-bold text-[10px] uppercase tracking-wider p-4">Product</TableHead>
                                        <TableHead className="font-bold text-[10px] uppercase tracking-wider p-4">Risk Level</TableHead>
                                        <TableHead className="font-bold text-[10px] uppercase tracking-wider p-4">AI Forecast</TableHead>
                                        <TableHead className="text-right font-bold text-[10px] uppercase tracking-wider p-4">Stock / Reorder</TableHead>
                                    </TableRow>
                                </TableHeader>
                                <TableBody>
                                    {isListLoading ? (
                                        Array(limit).fill(0).map((_, i) => (
                                            <TableRow key={i}>
                                                <TableCell className="p-4"><Skeleton className="h-10 w-full rounded-lg" /></TableCell>
                                                <TableCell className="p-4"><Skeleton className="h-10 w-full rounded-lg" /></TableCell>
                                                <TableCell className="p-4"><Skeleton className="h-10 w-full rounded-lg" /></TableCell>
                                                <TableCell className="p-4"><Skeleton className="h-10 w-full rounded-lg" /></TableCell>
                                            </TableRow>
                                        ))
                                    ) : products.length > 0 ? (
                                        products.map((product, i) => {
                                            const isCritical = product.riskLevel === 'CRITICAL';
                                            const isHigh = product.riskLevel === 'HIGH';
                                            const isMedium = product.riskLevel === 'MEDIUM';

                                            return (
                                                <TableRow key={i} className="hover:bg-muted/10 border-border transition-colors group">
                                                    <TableCell className="p-4">
                                                        <div className="flex items-center gap-3">
                                                            <div className="h-8 w-8 rounded-lg bg-primary/5 border border-border flex items-center justify-center">
                                                                <Package className="h-4 w-4 text-primary/60" />
                                                            </div>
                                                            <div className="flex flex-col">
                                                                <span className="font-bold text-xs">{product.productName}</span>
                                                                <span className="text-[9px] text-muted-foreground">SKU: {product.sku}</span>
                                                            </div>
                                                        </div>
                                                    </TableCell>
                                                    <TableCell className="p-4">
                                                        <div className="flex flex-wrap gap-1.5">
                                                            {isCritical ? (
                                                                <Badge className="bg-red-500/10 text-red-600 border-none rounded-md text-[9px] font-bold px-1.5 py-0.5 flex items-center gap-1">
                                                                    <AlertCircle className="h-2.5 w-2.5" /> CRITICAL
                                                                </Badge>
                                                            ) : isHigh ? (
                                                                <Badge className="bg-orange-500/10 text-orange-600 border-none rounded-md text-[9px] font-bold px-1.5 py-0.5 flex items-center gap-1">
                                                                    <TrendingUp className="h-2.5 w-2.5" /> HIGH RISK
                                                                </Badge>
                                                            ) : isMedium ? (
                                                                <Badge className="bg-yellow-500/10 text-yellow-600 border-none rounded-md text-[9px] font-bold px-1.5 py-0.5">MEDIUM</Badge>
                                                            ) : (
                                                                <Badge className="bg-green-500/10 text-green-600 border-none rounded-md text-[9px] font-bold px-1.5 py-0.5">LOW RISK</Badge>
                                                            )}
                                                        </div>
                                                    </TableCell>
                                                    <TableCell className="p-4">
                                                        <TooltipProvider>
                                                            <Tooltip>
                                                                <TooltipTrigger asChild>
                                                                    <div className="flex flex-col gap-0.5 cursor-help">
                                                                        <div className="flex items-center gap-1.5 text-[10px] font-bold">
                                                                            <Clock className="h-3 w-3 text-muted-foreground" />
                                                                            {isCritical ? (
                                                                                <span className="text-red-500">Stockout in {product.daysUntilStockout}d</span>
                                                                            ) : (
                                                                                <span>Stockout in {product.daysUntilStockout}d</span>
                                                                            )}
                                                                        </div>
                                                                        <div className="flex items-center gap-1">
                                                                            <div className="h-1 w-12 bg-muted rounded-full overflow-hidden">
                                                                                <div
                                                                                    className={`h-full ${isCritical ? 'bg-red-500' : 'bg-green-500'}`}
                                                                                    style={{ width: isCritical ? '90%' : '40%' }}
                                                                                />
                                                                            </div>
                                                                            <span className="text-[8px] text-muted-foreground font-bold">{product.trend} Trend</span>
                                                                        </div>
                                                                    </div>
                                                                </TooltipTrigger>
                                                                <TooltipContent className="rounded-xl p-3 shadow-xl border-border bg-background max-w-xs">
                                                                    <div className="space-y-1.5">
                                                                        <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">AI Reasoning</p>
                                                                        <p className="text-xs font-medium">{product.reasoning}</p>
                                                                    </div>
                                                                </TooltipContent>
                                                            </Tooltip>
                                                        </TooltipProvider>
                                                    </TableCell>
                                                    <TableCell className="p-4 text-right">
                                                        <div className="flex flex-col items-end gap-0.5">
                                                            <span className="font-bold text-xs">{product.currentStock} units</span>
                                                            {product.reorderQuantity > 0 && (
                                                                <span className="text-[9px] text-orange-500 font-bold">
                                                                    Reorder: {product.reorderQuantity}
                                                                </span>
                                                            )}
                                                        </div>
                                                    </TableCell>
                                                </TableRow>
                                            );
                                        })
                                    ) : (
                                        <TableRow>
                                            <TableCell colSpan={4} className="p-10 text-center text-muted-foreground text-xs">
                                                No inventory insights found. Run the Inventory Agent to generate predictions.
                                            </TableCell>
                                        </TableRow>
                                    )}
                                </TableBody>
                            </Table>
                        </CardContent>
                    </Card>
                </div>

                {/* Right Column: Intelligence Matrix (SaaS Style) */}
                <div className="lg:col-span-3 space-y-6">
                    <Card className="rounded-2xl border-border shadow-sm overflow-hidden">
                        <CardHeader className="p-5 border-b bg-muted/5">
                            <div className="flex items-center gap-2">
                                <Sparkles className="h-4 w-4 text-orange-500" />
                                <CardTitle className="text-sm font-bold uppercase tracking-wider">Inventory Matrix</CardTitle>
                            </div>
                        </CardHeader>
                        <CardContent className="p-0 divide-y divide-border">
                            {matrixSegments.map((segment, idx) => (
                                <div key={idx} className="p-4 hover:bg-muted/30 transition-colors cursor-pointer group">
                                    <div className="flex items-center justify-between mb-1">
                                        <div className="flex items-center gap-2">
                                            <div className={`p-1.5 rounded-lg ${segment.bg}`}>
                                                {segment.icon}
                                            </div>
                                            <span className="text-xs font-bold">{segment.name}</span>
                                        </div>
                                        <span className="text-[10px] font-bold text-muted-foreground">{segment.count}</span>
                                    </div>
                                    <div className="flex items-center justify-between mt-2">
                                        <div className="h-1.5 flex-1 bg-muted rounded-full overflow-hidden mr-3">
                                            <div
                                                className={`h-full ${segment.color.replace('text', 'bg')} opacity-60`}
                                                style={{ width: `${(segment.count / (total || 100)) * 100}%` }}
                                            />
                                        </div>
                                        <span className="text-[9px] font-bold text-muted-foreground">{Math.round((segment.count / (total || 100)) * 100)}%</span>
                                    </div>
                                </div>
                            ))}
                        </CardContent>
                        <div className="p-4 bg-orange-500/5 border-t border-border">
                            <div className="flex items-start gap-2">
                                <Zap className="h-3 w-3 text-orange-500 mt-0.5" />
                                <p className="text-[10px] text-muted-foreground leading-relaxed">
                                    AI is monitoring stock velocity to predict potential stock-outs.
                                </p>
                            </div>
                        </div>
                    </Card>

                    {/* Stock Health Card */}
                    <Card className="rounded-2xl border-border shadow-sm bg-gradient-to-br from-orange-500/5 to-transparent">
                        <CardHeader className="p-5 pb-2">
                            <CardTitle className="text-xs font-bold uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                                <BarChart3 className="h-3.5 w-3.5" />
                                Stock Health
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="p-5 pt-0 space-y-4">
                            <div className="space-y-2">
                                <div className="flex justify-between text-[10px] font-bold">
                                    <span className="text-muted-foreground">AVAILABILITY</span>
                                    <span className="text-green-500">{availabilityPct}%</span>
                                </div>
                                <div className="h-1.5 w-full bg-muted rounded-full overflow-hidden">
                                    <div className="h-full bg-green-500 rounded-full" style={{ width: `${availabilityPct}%` }} />
                                </div>
                            </div>
                            <div className="space-y-2">
                                <div className="flex justify-between text-[10px] font-bold">
                                    <span className="text-muted-foreground">WASTE RISK</span>
                                    <span className={wasteRiskColor}>{wasteRiskLevel}</span>
                                </div>
                                <div className="h-1.5 w-full bg-muted rounded-full overflow-hidden">
                                    <div 
                                        className={`h-full rounded-full ${wasteRiskPct > 20 ? 'bg-red-500' : wasteRiskPct > 10 ? 'bg-orange-500' : 'bg-green-500'}`}
                                        style={{ width: `${wasteRiskPct}%` }} 
                                    />
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>

            </div>
        </div>
    )
}
